### ISSUE TITLE
add support for other course versions

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-data-parser#53]
The linked versions of a course, as seen [here](https://ocw.mit.edu/courses/mathematics/18-01-single-variable-calculus-fall-2006/), should be included in master json in some capacity.

These items should be included:
 - [x] Open Learning Library Versions
 - [x] https://github.com/mitodl/ocw-to-hugo/issues/273 OCW Scholar Versions
 - [x] ~~https://github.com/mitodl/ocw-to-hugo/issues/275 MITx Versions~~
 - [x] https://github.com/mitodl/ocw-to-hugo/issues/273 Other OCW Versions
 - [ ] #141 Other OCW Versions ("archived versions")
 - [ ] Course Sequences
 - [ ] Course Collections ("Cross-Disciplinary Lists")
 - [x] ~~Course Collections ("Find Courses by Topic")~~
 - [x] ~~MIT Crosslinks~~

From @pdpinch :
1. “Open Learning Library” is probably an “additional feature” tag
2. Not sure about OCW Scholar…
3. I think MITx versions is completely handled in JavaScript, so you may not find anything at all
4. “Other OCW versions” is a link to retired version or previous versions or prior versions
5. I don’t know where “course sequence comes from. That might be managed in HTML
6. “Course Collections” is just another word for topics, so we already know where that is.

**Comment by gumaerc** [comment]
Findings so far:

#### In 1.json:
 - Open Learning Library entries are in `courselist_features` -> `ocw_feature` == "Open Learning Library".  The items are in `ocw_feature_url` separated by commas with the text and hyperlink separated by `::`
 - MITx versions are located at `courselist_features` -> `ocw_feature` == "MITx".  The title of the link is located in `ocw_subfeature` and the link is not included.
 - Crosslinks is located at `courselist_features` -> `ocw_feature` == "Crosslinks" and there is a link in `ocw_feature_url` but it seems to not be used and this object basically just serves as a boolean to serve up some pre-determined text.
 - Course Collections is already being pulled in as Topics.
 - Other OCW Versions, OCW Scholar Version and Course Sequence don't seem to be in the JSON exports and are potentially in "tabs" within the Plone CMS.  There are some action records that hint at this:
```
            {
                "action": "unlock", 
                "review_state": "unlocked_for_editing", 
                "comments": "Unlocked for adding course sequences in Related Content tab.", 
                "actor": "asingh33", 
                "time": "2015/07/23 03:34:17.217 GMT-4"
            }, 
```
            {
                "action": "unlock", 
                "review_state": "unlocked_for_editing", 
                "actor": "ndhamija", 
                "comments": "Unlock for adding Other Versions links to Scholar courses", 
                "time": "2013/03/28 04:12:03.645 GMT-4"
            }, 
```
            {
                "action": "unlock", 
                "review_state": "unlocked_for_editing", 
                "comments": "add 18.01SC link to Other Versions", 
                "actor": "pdpinch", 
                "time": "2014/10/24 12:37:28.502 GMT-4"
            }, 
```

```

**Comment by gumaerc** [comment]
MITx versions are generated by `edxcourselinking.js`:

```js
    // code for positioning MITx version in other versions tab	
    if ($("#versions").length==0){		
         $('#description').after('<h2><a href="#versions">Other Versions</a></h2><div id="versions"><div></div></div>');		
         }
     if (flag ==true){
            if ($("h2:contains('OCW Scholar version:')").length > 0){
                $("h2:contains('OCW Scholar version:')").next("ul").after(edx_common_text + edx_display_text); //Appending after OCW Scholar Version
             }  
			else if ($("h2:contains('OCW Scholar Version')").length > 0){
                $("h2:contains('OCW Scholar Version')").next("ul").after(edx_common_text + edx_display_text); //Appending after OCW Scholar Version
             }  
            else if ($("h2:contains('Other OCW Versions')").length > 0){
                $("h2:contains('Other OCW Versions')").before(edx_common_text + edx_display_text); }// Appending before Other OCW Versions
            else {$("#versions").append(edx_common_text + edx_display_text); } // Appending to Other Versions tab when only Other Versiov FCK editor text is present
            }
    else{$("h2:contains('MITx Versions')").next().last().after(edx_common_text + edx_display_text); }
```
